### ISSUE TITLE
no snaps or mobile apps on https://uappexplorer.com/ 

### ISSUE THREAD

**Issue by Alculete** [bhdouglass/uappexplorer#104]
https://uappexplorer.com/ page it doesn't have any snap listed. Is the is purpose or a bug?

**Comment by bhdouglass** [comment]
That's just an oversight, I'll have to update that main page.

**Comment by Alculete** [comment]
OK, I thought you decided to close the page. This is a must go page for all snap lovers to find new apps.
Thank you for the good work by the way

**Comment by bhdouglass** [comment]
I've updated the main page so you can now see the new snaps under the new phone apps. I haven't closed the page, just have been working on other projects.
