### ISSUE TITLE
Snap Search Category Paramater Broke

### ISSUE THREAD

**Issue by OMHM** [bhdouglass/uappexplorer#106]
URL:https://uappexplorer.com/snaps?category=ops

The search query paramater for category returns 0 results for all category variables.

**Comment by bhdouglass** [comment]
Looks like the categories must have changed again, I'll look into that.

**Comment by OMHM** [comment]
Thank you, I would have fixed it but I figured you need sysadmin priveleges so I didnt bother. Have a good one.
-

**Comment by bhdouglass** [comment]
They're all up to date now!
