### ISSUE TITLE
Show similar apps when looking at an app in detail

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#39]
In addition to the suggestion in issue #38 it would be cool to also add a row of similar apps. To be honest, I don't know how this will work or be implemented on your end but I could think of a few suggestions,

Perhaps show apps using the same tags as the current app being currently seen. So if I am looking at the clock app, then other apps like Timer, Stopwatch made by others will appear. 

(This issue and issue #38 were suggested by someone who reviewed your app)

**Comment by bhdouglass** [comment]
I saw that review and add the request to my todo list :)
#38 will be pretty simple. This one might not be as simple. The only thing making the apps similar is the keywords and the category, so I'm not sure how well that will work. Guess we'll just have to see!

**Comment by bhdouglass** [comment]
I just added this feature. It turned out ok using the keywords and the category, but I'm looking for ways to improve it.

**Comment by krnekhelesh** [comment]
Look good. In my initial testing, it seems to return sensible results and worked fine.

**Comment by bhdouglass** [comment]
Awesome!

**Comment by AdricoM** [comment]
Hi !
I might be the one who wrote the review and I must say that it is great work done, thanks !

**Comment by bhdouglass** [comment]
Glad you like it!
