### ISSUE TITLE
Wishlist: allow to search/filter by licence (All/Opensource/Proprietary)

### ISSUE THREAD

**Issue by Talkless** [bhdouglass/uappexplorer#40]

**Comment by bhdouglass** [comment]
I just added this under the "Filters" section. Let me know if that works for you!

**Comment by Talkless** [comment]
40 pages of open source apps vs 9 of propietary. Way to go Ubuntu ! :+1: 

Thank you for this feature.

**Comment by bhdouglass** [comment]
I saw that, pretty awesome :smile: 

Any time!
