### ISSUE TITLE
Landing page doesn't show search button

### ISSUE THREAD

**Issue by galgalesh** [bhdouglass/uappexplorer#41]
Every time I go to the landing page, I'm very confused. Is there no search functionality? The search functionality is a very powerful feature of uappexplorer, and I think you should highlight it better on the landing page.

Possible solutions:

- Put a "Search" menu item in the top menu
- Put a "Search" box in the top menu (that searches everything by default)
- Change the "Browse" header to "Search"

**Comment by bhdouglass** [comment]
I'm pretty sure I'm going to move the search box into the top menu (if I can make it work nicely). I'm almost done with another feature then I'll get on this.

**Comment by bhdouglass** [comment]
Just move the search bar into the navbar, so it's available all the time. Let me know what you think!

**Comment by galgalesh** [comment]
Looks great! Thanks!

2015-06-03 17:20 GMT+02:00 Brian Douglass <notifications@github.com>:
