### ISSUE TITLE
Do not reload when pressing the back button

### ISSUE THREAD

**Issue by nikwen** [bhdouglass/uappexplorer#42]
Currently, when going back to the overview page from an app page, it has to reload the list of applications. I'd prefer the site to just show the results it showed before initially clicking on the app.

Check out m.bbc.com as an example of what I mean.

**Comment by bhdouglass** [comment]
Are you talking about the back button in the app or in your browser (or both)? I think I have a todo comment somewhere to fix that.

**Comment by nikwen** [comment]
Actually, I was referring to both. ;)

**Comment by bhdouglass** [comment]
The I'll fix both!

**Comment by bhdouglass** [comment]
Just fixed this, the list is cached so it won't have to reload when going back.

**Comment by nikwen** [comment]
Thanks for fixing this. :)

However, now it seems to me as if loading app detail pages takes forever until all images on the overview page have loaded.

**Comment by bhdouglass** [comment]
If you are referring to the screenshots loading slowly that's probably because they are hosted by Ubuntu and not uApp Explorer (but the app icons are). It wasn't really feasible to host copies of the screenshots so they are unfortunately slower.

**Comment by nikwen** [comment]
No, I didn't mean that. As I am, however, not seeing that behaviour anymore, I believe it was an issue related to too much traffic coming in at the same time. Thank you anyway. :)

**Comment by bhdouglass** [comment]
Yeah that could be it.
