### ISSUE TITLE
Adding apps to the user lists is a bit cumbersome

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#44]
First huge props to the user accounts feature! This introduces a huge array of possibilities. Great Work! At the moment, the only way to add an app to a user list is by navigating to the app's page and then clicking add to list. This makes it difficult to quickly create a list with 10-15 apps.

Would it possible to include a "Add App" button in the user list page? The workflow I had in mind was,
1. User creates a new list
2. User presses the "Add app" button which opens a search dialog overlay
3. User searches for app and then from the search results is able to quickly add to the list

The user keeps repeating step 3 to add more and more apps to the list.

**Comment by bhdouglass** [comment]
That workflow makes sense to me, I'll see about adding it in.

**Comment by bhdouglass** [comment]
Just implemented adding and removing apps from lists when you go to edit them.

**Comment by krnekhelesh** [comment]
Works great! I like the show results as you type feature..pretty cool

**Comment by bhdouglass** [comment]
Great!
