### ISSUE TITLE
Provide the ability to share user lists to G+, facebook etc

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#45]
What it says in the title

**Comment by bhdouglass** [comment]
There are links to share on social media if you go to the list view. This may be related to #46.

**Comment by krnekhelesh** [comment]
Yup this is related to #46 where disabling adblocker showed the share butons in the list view.

**Comment by bhdouglass** [comment]
I'm going to close this out then since it duplicates #46 and just do the fix there
