### ISSUE TITLE
Social share buttons missing in the desktop

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#46]
In the desktop mode, social share buttons are missing in the app page as seen in https://imgur.com/g6Ofo0V. It is fine to not show them (for whatever reason you may have had), but you might not want to show empty space there in that case.

**Comment by bhdouglass** [comment]
Do you have an adblocker running? It's probably hiding the icons based on their names. I've got my adblocker configured to no run on uappexplorer.com. I'll look into a way around this without having to explicitly disable the adblocker.

**Comment by krnekhelesh** [comment]
ah yes you were right...I had adblocker enabled for all websites...disabling it for uappexplorer seems to have fixed it. Personally this issue is fixed for me, but feel free to keep it open to find a way to show the buttons without explicitly disabling adblocker.

**Comment by bhdouglass** [comment]
Just fixed this, the links should show despite an adblocker.
