### ISSUE TITLE
Unable to login in the UT app

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#47]
In the UT app, when the user presses on login via Ubuntu SSO, it opens the browser and as such the app itself does not get the token required to login.

**Comment by bhdouglass** [comment]
Oops, fix it! Now you stay in the app when logging in.

**Comment by krnekhelesh** [comment]
Nice rapid fix!

**Comment by bhdouglass** [comment]
Any time! :)
