### ISSUE TITLE
Collapse top header after pressing on a link

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#48]
On the phone after pressing a link in the header, it still stays open and takes a lot of space. it would be beneficial to auto-collapse it after clicking on a link.

![header](https://cloud.githubusercontent.com/assets/761845/7945785/3878b0d6-0973-11e5-87f2-23d989c2ade1.png)

**Comment by bhdouglass** [comment]
It's weird that doesn't close automatically. I'll get it fixed.

**Comment by bhdouglass** [comment]
Fixed!
