### ISSUE TITLE
List page content is a bit disorganized on the phone layout

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#49]
If you look at the screenshot things are a bit disorganized as in the share buttons are right-aligned and appear below the filter buttons while this is not the case in the regular app details page.

![content-inorganized](https://cloud.githubusercontent.com/assets/761845/7945845/89ec2a10-0973-11e5-9055-7b758ef878d2.png)

**Comment by bhdouglass** [comment]
I'll make the spread out to take up all the available space.

**Comment by bhdouglass** [comment]
Just uploaded ad spread-out version of this, enjoy!
