### ISSUE TITLE
Swipe between apps from a list

### ISSUE THREAD

**Issue by stuartlangridge** [bhdouglass/uappexplorer#50]
The app store scope on the phone has the nice property that if you're looking at a list of apps (a category, new apps, etc) and you tap an app to show it in detail, you can swipe left and right to go to the next or previous app in the list without having to return to the list to pick the next one. It'd be cool if uappexplorer could do the same.

**Comment by bhdouglass** [comment]
That would be cool, and shouldn't be too hard to implement. I'll get on it!

**Comment by bhdouglass** [comment]
Just added this, enjoy!
