### ISSUE TITLE
Impossible to scroll all the screenshots because of swiping gesture

### ISSUE THREAD

**Issue by AdricoM** [bhdouglass/uappexplorer#51]
Hi !
Swipe gesture to navigate through apps is cool but when there is a horizontal scroll for the screenshots, it is impossible to just scroll to see thumbnails of all the pictures

Thanks in advance for taking this into account,
AdricoM

**Comment by krnekhelesh** [comment]
I face this issue as well, at first I thought it was unity8 stealing focus or something before realizing that the horizontal app scroll could be the culprit.

**Comment by bhdouglass** [comment]
Oops, I'll get this fixed!

**Comment by bhdouglass** [comment]
Just released a fix for this! Let me know how it works.

**Comment by AdricoM** [comment]
Works well know, thanks !

**Comment by bhdouglass** [comment]
Great!
