### ISSUE TITLE
From scope, see the detail of any app in the app and not in the browser

### ISSUE THREAD

**Issue by AdricoM** [bhdouglass/uappexplorer#52]
Hi,

From the scope, when I want to see the detail of an app, it opens me the web browser, is it possible that when uapps web app is installed, it were this app that opens instead ?

Thanks in advance !
AdricoM

**Comment by bhdouglass** [comment]
I just added this ability, you'll need to update the webapp. Let me know how that works for you!

**Comment by AdricoM** [comment]
Works well after update, great ! :-)

**Comment by bhdouglass** [comment]
Awesome!
