### ISSUE TITLE
[Scope] Add more details to the app preview

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#53]
It would be nice to see more detail to the app previews like,
- Detailed app description instead of the current one line description being shown.
- App license (Open-source, proprietary)
- Show heart rating by using icons like uappexplorer.com does to make it more pleasing.

I basically think that except for seeing comments or installing an app, everything should be doable within the app preview. Since I haven't dabbled in scope development, I have no idea what is feasible and what's now.

**Comment by bhdouglass** [comment]
It is definitely feasible, I just haven't gotten that far yet. Currently the scope is just a minimum viable product.

**Comment by bhdouglass** [comment]
I just uploaded v1.2 of the scope to the store. It's go a bunch more detail in the app preview. The only thing I haven't figured out yet is how to make the heart and star ratings look nicer.

**Comment by krnekhelesh** [comment]
Nicely done! The preview page is now more useful and reduces the need to open the webapp. I have an idea for the heart & star ratings design,

Here is a picture of the star rating shown in a cinema scope made by a community member. You can find the source code of his scope [here](https://github.com/dslul/cinema-scope).

![1](https://cloud.githubusercontent.com/assets/761845/8765350/263526c0-2e08-11e5-8556-602e708e8968.png)

**Comment by bhdouglass** [comment]
Oh that's how you do that, I was trying something similar but it ended up being a flop.

**Comment by bhdouglass** [comment]
Just uploaded v1.3 with a much better star rating, thanks!

**Comment by krnekhelesh** [comment]
Did anyone mention how awesome you are ;)

**Comment by bhdouglass** [comment]
haha, thanks :)
