### ISSUE TITLE
[Scope] Add ability to login into the ubuntu account and see user scopes

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#54]
There are some scopes like youtube, facebook etc that allow users to login to their account and display personalized content. In uappexplorer's case that could be showing the user's lists.

**Comment by bhdouglass** [comment]
Hmm.. I'll have to do some research on how to best set this up (because of the complex sign in process).

**Comment by bhdouglass** [comment]
@krnekhelesh do you mind moving this over to the scope repo?

**Comment by krnekhelesh** [comment]
Closing this bug as it has been moved this bug report over to the correct project.
