### ISSUE TITLE
[Scope] Add action button to add/remove an app from a user list

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#55]
This first requires being able to login into the user account and once that is available be able to add/remove apps from lists.

I believe this is the direction that scopes are heading towards in general. Providing some basic actions like tweeting/replying/commenting etc .. with uappexplorer that would be adding/removing apps from lists.  

Add a more button which houses the above actions like "add/remove app from list", "liking" etc.

Stuff like creating lists can be app exclusive.

**Comment by bhdouglass** [comment]
I like it :)

**Comment by bhdouglass** [comment]
@krnekhelesh do you mind moving this over to the scope repo?

**Comment by krnekhelesh** [comment]
Sure, so do I close it and create a new report at the scope repo?

**Comment by bhdouglass** [comment]
Yeah, I don't think you can "move" issues in Github.

**Comment by krnekhelesh** [comment]
Closing this bug as it has been moved this bug report over to the correct project.
