### ISSUE TITLE
[Scope] Design Improvements

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#56]
Here are 2 pictures of the cinema scope where we can borrow some design from,
- Using bold letters to highlight section names like "Genres", "Cast" etc..for the uapp explorer scope words like "License", "Version", "Scope,App", "Publisher/Creater", "Contact" etc could be highlighted in a similar fashion

![1](https://cloud.githubusercontent.com/assets/761845/8765355/6998bb66-2e08-11e5-97d9-47eb023a6f8d.png)
![2](https://cloud.githubusercontent.com/assets/761845/8765356/6ad6ce0a-2e08-11e5-8b6e-05d6094b58d5.png)

**Comment by bhdouglass** [comment]
I like bolded text idea, but so I can have a sense of accomplishment, lets move the second part of the request over to #55 then this one can be easily closed out. :)

**Comment by krnekhelesh** [comment]
Sure, fair point. Moving the second list item request over to bug #55 :-)

**Comment by bhdouglass** [comment]
Done in v1.3!

**Comment by krnekhelesh** [comment]
Looks much better!
