### ISSUE TITLE
[Scope] Add categories to filter content

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#57]
I can think of 2 types of filtering that can be done taken straight from the website,

- First filter to view Apps, Scopes, WebApps, All. That would be a killer feature that differentiates your scope from the official store scope.

- Second filter for different categories like "Communication", "Utility", "Games" etc etc...similar to what is already present on your website.

The design can be as follows :-),

Source: https://github.com/dslul/cinema-scope

![4](https://cloud.githubusercontent.com/assets/761845/8765381/38782b60-2e09-11e5-9180-3c6a28d40d27.png)
![5](https://cloud.githubusercontent.com/assets/761845/8765382/3a7f2e9a-2e09-11e5-8e08-122c40e44d8a.png)

**Comment by bhdouglass** [comment]
This should be pretty easy once I figure how to do it. :)

**Comment by bhdouglass** [comment]
Done in v1.3!

**Comment by krnekhelesh** [comment]
Looks and works great! Thanks for the feature.
