### ISSUE TITLE
[Scope] Match webapp header style

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#58]
Scope headers allow branding. For uapp explorer, I think using a "logo + Uapp Explorer" on a blue background would be a nice branding for the scope. An example below,

![10](https://cloud.githubusercontent.com/assets/761845/8771258/815e189c-2ebf-11e5-88cb-2af8ae2bff57.png)

**Comment by bhdouglass** [comment]
Done in v1.3, thanks for the suggestion!

**Comment by krnekhelesh** [comment]
Not sure if this bug has been fixed since the header is still white and looks the same. Are you sure you pushed this as well?

**Comment by krnekhelesh** [comment]
Ignore me..I just unfavourited and then readded the scope and I see the new blue header now. Previous the new features were there except for the heaðer style. Strange.

**Comment by bhdouglass** [comment]
Yeah, I had to do stuff like that to properly test it.
