### ISSUE TITLE
a way to monitor newly published / updated apps needed

### ISSUE THREAD

**Issue by lugovsa** [bhdouglass/uappexplorer#59]
As a user I would be happy to have an RSS-feed, twitter, scope or something informing me about the appearing of new apps and updating of existing apps. BTW, that wold also attract more users to the project.

**Comment by bhdouglass** [comment]
We actually have a twitter page, google+ page, and two rss feeds already setup. You can find links to them at the bottom of any page on uappexplorer.com. Let me know if there is any way they can be improved!
