### ISSUE TITLE
[Feature Request] Add download button to app page

### ISSUE THREAD

**Issue by brunonova** [bhdouglass/uappexplorer#62]
If possible, please add a download button to the application page (maybe besides the "Install" button), to download the .click/.snap package.

This would be useful for people not using click/snappy yet (like me), but that would like to inspect these packages.
It would probably also be useful for people that want to sideload an app (possibly after modifying the package).

**Comment by bhdouglass** [comment]
I've recently added a download button for snappy packages (it replaces the install button). I don't think I can support downloads of click packages as they are not publicly downloadable.

**Comment by brunonova** [comment]
Great!

> I don't think I can support downloads of click packages as they are not publicly downloadable.

That sucks.
But, Snappy will eventually replace Click, so it's not too bad.

**Comment by eyelash** [comment]
I haven't tries this but on https://wiki.ubuntu.com/AppStore/Interfaces/ClickPackageIndex there is an example of downloading a click package for an authenticated user. Downloading click packages would be nice especially for installing click apps on the desktop where the click scope does not work.

**Comment by bhdouglass** [comment]
I've seen that and it's a different kind of authentication than the one used to log into uApp Explorer. Downloading the packages is supported internally for parsing, but it's not something that can be easily user accessible as far as I can tell.
