### ISSUE TITLE
"Install" button could go directly into installation page instead of Search Result

### ISSUE THREAD

**Issue by gang65** [bhdouglass/uappexplorer#63]
"Install" button could go directly into installation page instead of Search Result.

I installed application uAppExploerer:
https://uappexplorer.com/app/uappexplorer.bhdouglass

I love it. It is user friendly, have Heart rate, and allows easily search within different categories.

One thing is annoing me: When I'm trying to install new application from uAppExploerer, and click "Install" button, the Ubuntu Store is displayed with Search items.

 Expected: I would like to uAppExploerer get me directly into application installation page.

Is it possible to implement it in uAppExploerer?
If no where I should report such bug?

**Comment by bhdouglass** [comment]
I would love to have the links go directly to install page rather than the search page. Unfortunately there is no support for this from the Unity shell. I've already created a bug for it that you could add a "me too" to - https://bugs.launchpad.net/ubuntu/+source/unity-scopes-shell/+bug/1492252
