### ISSUE TITLE
Allow sorting by "Heart rate", only according ratings from specific language/location

### ISSUE THREAD

**Issue by gang65** [bhdouglass/uappexplorer#65]
It will be great to allow sorting by "Heart rate", only according ratings from specific language/location.
It is default feature on other stores (Android, Apple etc).

Example:
Let's say we have fahrplan application:
https://uappexplorer.com/app/com.ubuntu.developer.mzanetti.fahrplan2

It is very popular but it could be used only in specific locations. For example there is no Polish trains.
In such feature, because there is no Polish Trains there, that's why Heart Rate from Polish guys will be low (or zero). 

Result: 
List of proposal applications will better fit needs of local users.

**Comment by bhdouglass** [comment]
I know we talked about this on telegram, but I just wanted to re-post it here. This does appear to be possible because the Ubuntu app store provides the language for the user leaving the review. So it should just be a matter of me implementing this feature.

**Comment by bhdouglass** [comment]
Closing this issue as I don't feel it's relevant any more after the news that Canonical is no longer driving Ubuntu Touch.
