### ISSUE TITLE
Items from lists keep dissapearing.

### ISSUE THREAD

**Issue by mindaugasdi** [bhdouglass/uappexplorer#66]
I tried adding apps to the list, but I have not succeded adding more than 3 items. Either some of the items dissapear, or all of the older items dissapear then I add a new one.

This is web version.
Apps are added through the app view.

**Comment by bhdouglass** [comment]
Thanks for the bug report, I see where the problem lies and I will fix it soon.

**Comment by bhdouglass** [comment]
I've just fixed this, let me know if you have any other problems!

**Comment by mindaugasdi** [comment]
Great:)
