### ISSUE TITLE
OSMScout

### ISSUE THREAD

**Issue by ombriano** [bhdouglass/uappexplorer#67]
I am a mapper for OpenStreetMap and made many updates.
I tried to work on the file downloaded from OSM in OSMScout use that, but I did not succeed.
There is clear guidance on how to do?
Or when he comes reconstructed the map of Italy?
Thank you
Use the Google translator, I hope it is clear what is written

**Comment by bhdouglass** [comment]
This isn't the right place if you need help with OSMScout. You probably wasn't to contract the author of OSMScout.
