### ISSUE TITLE
[bug] Popin constantly appears if cookies disabled

### ISSUE THREAD

**Issue by tetraf** [bhdouglass/uappexplorer#68]
The "Welcome to uApp Explorer!" modal popin keeps appearing each time I (re)load a page if I disable cookies, which are not really needed if not logged in, except for language but it could be detected from Accept-Language HTTP header.
The text of the popin may be put elsewhere in the page or in the FAQ.

**Comment by bhdouglass** [comment]
I would rather leave the popup as is. So I'll look into using localStorage as a backup method or something.

**Comment by bhdouglass** [comment]
I just changed it so you shouldn't get the popup constantly. Let me know if you have any other problems!

**Comment by tetraf** [comment]
Perfect, thanks.
