### ISSUE TITLE
Allow comments on Wishlist items

### ISSUE THREAD

**Issue by elimisteve** [bhdouglass/uappexplorer#69]
For example, it would be awesome if at pages like https://uappexplorer.com/wishlist/5678fe66956adffff2fc603f , users could provide more detail.

I am developing for Ubuntu Phone right now and am super interested in hearing from more users regarding what they want on the platform, as to speed up adoption.  Being able to see exactly what they want, and even having conversations on there with people about why they want certain features, and which features are most important to add first, would be _amazing_.

Are you open to such a feature?  Hmm, idea: what about dropping in a [Disqus chat widget](https://disqus.com/admin/universalcode/), so in some sense _no one_ needs to implement this feature in order for everyone to enjoy it?

**Comment by bhdouglass** [comment]
Thanks for the idea! I would be open to it, I would just need to figure out how to best implement it. Disqus is probably the simplest solution, I'll need to investigate it some more.

**Comment by elimisteve** [comment]
@bhdouglass I'd bet we could figure it out in 1 hour flat. What do you think? We could find tutorials online, collect a few links, then chat in real-time (text? audio? audio + video?) to finish it off. What do you think? Tuesday works for me.  Let me know; I really want this feature so I and the rest of the Ubuntu Phone developers can get relevant feedback from real users regarding what they want us to build!  Thanks.

And great thinking with the "How much would you pay for this?" question; that helps, too.

**Comment by bhdouglass** [comment]
I'm most certainly open to collaboration, biggest problem for me is lack of time. You can hit me up on telegram (@bhdouglass) if you've got that.

**Comment by bhdouglass** [comment]
Closing this issue as I don't think the wishlist is relevant any more.

**Comment by elimisteve** [comment]
RIP Ubuntu Phone :'-(.

I'll probably run Copperhead OS. And you?

**Comment by bhdouglass** [comment]
I'm thinking about seeing how well Android runs on my m10.
