### ISSUE TITLE
Star rating incorrect - (4 + 5) / 2 = 3,77

### ISSUE THREAD

**Issue by weeman1337** [bhdouglass/uappexplorer#71]
The star rating seems to be incorrect. #14 says "The star rating comes from the API. It may be wrong, so I calculate it by myself.". As you see in th attached screenshot, there are two ratings: 4 and 5. Here I'm expecting (4 + 5) / 2 = 4,5 star rating. But it displays 3,77.

You can check it currently on https://uappexplorer.com/app/eu.michael-weimann.stock-n-roll

![screenshot from 2016-02-26 19-25-52](https://cloud.githubusercontent.com/assets/6216686/13361440/f396bdb2-dcbe-11e5-9b79-867e3f1b8f2d.png)

**Comment by bhdouglass** [comment]
The star rating isn't actually a strict average of the star ratings, it's a Bayesian average of the ratings. From the FAQ:

> The star rating is the Bayesian average of the star ratings that user give to an app when they leave a review. The Bayesian average allows apps with more reviews to rank better than apps with less reviews. The star rating can be between 1 and 5, where a 0 means that there have not been any reviews yet.

So it is expected that your math doesn't add up.

**Comment by weeman1337** [comment]
Should have read the FAQs. But who does...? ;) Just saw the two ratings and the calculated rating and it didn't fit for my feeling...  If this request comes up from time to time, may it be an idea to place e.g. a little exclamation symbol there with a tooltip/link to the FAQ item?

Anyway excellent response time for an issue! Thanks

**Comment by bhdouglass** [comment]
Haha while answering you that thought did cross my mind. It might be a worthwhile addition.
