### ISSUE TITLE
It is no more possible to delete an App from My Lists

### ISSUE THREAD

**Issue by VosaXalo** [bhdouglass/uappexplorer#73]
On my list of apps, I want to delete one element, but if I click on the little cross on the right nothing happens. It should delete the app.

**Comment by bhdouglass** [comment]
I just checked and I don't seem to be having an issue. What browser are you using?

**Comment by VosaXalo** [comment]
I have tried with Chromium, Vivaldi, Firefox, Chrome, and also with the App on my Ubuntu Phone, but the behavior it is always the same. The little cross to delete an App does nothing.

**Comment by bhdouglass** [comment]
Do you happen to have something like an adblocker on your router? I can't seem to replicate this issue.

**Comment by VosaXalo** [comment]
No, I'm sure I don't have something like an adblocker.
I have tried from two different PC on two different networks.
And on my Ubuntu Phone I don't even use the wifi connection, but my data (4G) connection.
I don't know if this can help, but it is enough time that I use your site, and previously all worked well, but I can't say since when there is the issue.

**Comment by bhdouglass** [comment]
What desktop and phone versions do you have?

**Comment by bhdouglass** [comment]
What was the app you tried to remove? Also, if you refresh the page does it disappear?

**Comment by VosaXalo** [comment]
The desktop I have used are: Windows 7 and Ubuntu 14.04 LTS (the main one)
The phone is the Meizu MX4 updated to OTA 9.1 (up to date).

I have tried to remove different apps, but the behavior is always the same. I have also tried to refresh the page, but the app is still there.

**Comment by bhdouglass** [comment]
Thanks to some help trackinf this down, I think this has more to do with the contents of the list (usually an app that had been removed from the store). Can you send me a link to your list so I can confirm? I'm currently working on a fix.

**Comment by VosaXalo** [comment]
The link to my list is: https://uappexplorer.com/list/556ff7c0863ea1735e138052
And the app I am trying to remove is Utudu.

Thanks!

**Comment by bhdouglass** [comment]
OK I believe I've fixed the issue, let me know if it works for you!

**Comment by VosaXalo** [comment]
Now it's perfect!
Thank you very much!

**Comment by bhdouglass** [comment]
Awesome!
