### ISSUE TITLE
Default app type "All Types" doesn't show snappy apps

### ISSUE THREAD

**Issue by krnekhelesh** [bhdouglass/uappexplorer#74]
I understand why snappy apps are not shown by default (not in production yet and so on..)..but I noticed that by default the filter is "All  Types" and this doesn't show snappy apps. But if I switch to another type and then back to "All Types", this time the results also include snappy apps. This is a bit confusing. May be have, Click App and Snappy Apps as filters. Default to Click Apps. This way you don't change your default behavior while at the same avoid confusion.

**Comment by bhdouglass** [comment]
I haven't been able to replicate switching back to "All Types" and it still showing snappy apps, could you walk me through that?

As for changing the label, yes I agree that it is confusing. I think I might call it "Phone Apps" for now (since non-technical users won't know what a click is).

**Comment by bhdouglass** [comment]
I've changed "All Types" to "Phone Apps & Scopes" and updated the site today.
