### ISSUE TITLE
snap package links are ignorant of architecture variation

### ISSUE THREAD

**Issue by chadmiller** [bhdouglass/uappexplorer#75]
Snap packages are bound to a machine architecture. An uploader will fabricate powerpc, amd64, etc etc, and upload.

I think only the most recent file uploaded will appear as "download" link, even when there are many versions  and architectures published.

Example: only i386 here:  It should be that and three others.

https://uappexplorer.com/app/tor-middle-relay.chadmiller

**Comment by bhdouglass** [comment]
I can't seem to find that app via the click store api to find if there are other links. Do you have another example?

**Comment by chadmiller** [comment]
No, but I uploaded that app. In fact, I uploaded the most important arches
first. i386 is the last because it's least likely to be used, and is the
only link you have.

In you have 16.04 snappy installed, you'll get the right packages for
amd64, armhf, arm64, etc, whatever is your native architecture. That says
there is a way to poll. There could be a problem with the API you're using.

Beware also that in that store, it's normal to have several versions
published.

The package/architecture/version/uniqueness data schema from the deb days
doesn't apply to snaps.
On Apr 13, 2016 10:24 PM, "Brian Douglass" <notifications@github.com> wrote:

I can't seem to find that app via the click store api to find if there are
other links. Do you have another example?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/bhdouglass/uappexplorer/issues/75#issuecomment-209728428>

**Comment by bhdouglass** [comment]
I did end up finding your snap (for my future reference, it is here: https://search.apps.ubuntu.com/api/v1/package/9LIlp9GNiC3BFymbAPOoo1V5yIILeKBP ). It seems that the api is only telling me that it's got an i386 arch unless I tell the api that I'm using a different arch. I'll need to reach out to the click api gurus and see if I can get the api to give me the information that I need.

**Comment by chadmiller** [comment]
This is the weird part. I don't think you will find a dimension of architectures and download links. You have a string now, and you won't get an array of strings instead.

In the package page I see at "myapps", revision 8 is the i386 package, version 0.2.7.6-3. Revision 7 is the armhf one, same version. Revision 6 is the arm64, Revision 5 is amd64. Revision 4 is amd64 and version 0.2.7.6-2 *but still published*. Revision 4 is an earlier, but not published.

I suspect (but do not know!) each of those is a different UUID for you to look up at an earlier stage, instead of components of one package manifest like you found above.

**Comment by bhdouglass** [comment]
That's kind of a weird way to do the different architectures, but it probably explains why uApp Explorer only sees the last one. I don't believe that I can query for a specific revision. It will give me the different architectures from the same "package_id" (provided I query with a different architecture). I'm going to still reach out to the click api dev to see if I can convince them to change it a bit.

**Comment by bhdouglass** [comment]
I've devised a new method of parsing the data from the api. It will give me the data on each different architecture. I'll be implementing that during the next couple days and I'll update you when it's ready to be reelased.

**Comment by chadmiller** [comment]
Ah, something else for you to pay attention to, in addition to the arches:  Release.

All the packages you saw until now were for a "Supported Release" of "rolling-core". I had to add new packages yesterday to support what is actually going to show up in Ubuntu, "Supported Release" "16".

So, you might want to differentiate by Supported Release first, then list each architecture.

**Comment by bhdouglass** [comment]
Thanks for the heads up! I'll take a look at that.

**Comment by bhdouglass** [comment]
I've released an update to uApp Explorer last night that supports packages with multiple arch's. Check it out and let me know if you have any other issues!
