### ISSUE TITLE
Search by author does not show results of apps by the author

### ISSUE THREAD

**Issue by codersquid** [bhdouglass/uappexplorer#76]
Hi, I noticed this when browsing to https://uappexplorer.com/app/notes.notes-developers from a blog post about the Notes app.

That page has [a link for the authors](https://uappexplorer.com/apps?q=author%3ANotes+Developers), but that link isn't showing any results, not even for the Notes app.

**Comment by bhdouglass** [comment]
The author search pages shows phone apps by default, since that notes app is a snappy app you would need to change the filters to see it.

**Comment by codersquid** [comment]
Thanks, I didn't catch that at first. I can work around it now.

For a feature, I'd like to see all types of apps by an author.

**Comment by bhdouglass** [comment]
Yeah it's probably a good idea to add a filter for all apps (both phone and snappy) since snappy is gaining a lot of momentum.

**Comment by bhdouglass** [comment]
I've added an "All Types" filter that will show both phone apps and snap apps. I've also made this the default when clicking on the author's name to clear up any confusion.
