### ISSUE TITLE
Segment snaps by release

### ISSUE THREAD

**Issue by noise** [bhdouglass/uappexplorer#77]
Snaps changed dramatically between the "15.04-core" release and the current "16" release and are not compatible across releases.  Thus it would be good to be able to segment/filter by the release. This can be done by passing X-Ubuntu-Release header to the search API with one of the above values.

**Comment by bhdouglass** [comment]
That sounds like a great filter, I'll work on getting that in.

**Comment by noise** [comment]
@bhdouglass thanks, let me know if you need any help. Also, we are nearly complete with some new snap-specific endpoints, docs here:

https://search.apps.ubuntu.com/docs/#snap-specific-endpoints

**Comment by bhdouglass** [comment]
Any help would be appreciated! Thanks for the heads up on the new endpoints, I'll check them out.

**Comment by bhdouglass** [comment]
I've added a new filter for releases, check it out!

**Comment by noise** [comment]
Looks good, thanks!

It could be useful to default to 16 since that's what most people will be looking to install on classic or device images (soon), but then you'd need to make that obvious in the UI.

**Comment by bhdouglass** [comment]
I think I'll leave it as is for now, and revisit it again in the future.
