### ISSUE TITLE
qownnotes will not be found

### ISSUE THREAD

**Issue by pbek** [bhdouglass/uappexplorer#78]
First and foremost, thank you for the great web-service! :tada: 

Is there a reason that <https://uappexplorer.com/app/qownnotes.pbek> will not be found in the search with `qownnotes`? Or does the search index just need some time to be updated?

**Comment by bhdouglass** [comment]
I'm glad you like it!
I'm not sure why it wasn't in the search, but I've got it in there now! Thanks for the heads up.

**Comment by pbek** [comment]
@bhdouglass, do you already see it? I still doesn't get a result with <https://uappexplorer.com/apps?q=qownnotes&sort=relevance>

**Comment by bhdouglass** [comment]
You have to change the filter, by default only phone apps show up in the search: https://uappexplorer.com/apps?q=qownnotes&sort=relevance&type=snappy

**Comment by pbek** [comment]
Ah, I see. I didn't recognized that, I just tried `Apps` :) Thank you for making that clear to me!

**Comment by bhdouglass** [comment]
No worries, as snaps continue to gain popularity I'll need to make some changes to the default filters.

**Comment by pbek** [comment]
Yay! ^_^
