### ISSUE TITLE
"next" button not working after first item of next page of results

### ISSUE THREAD

**Issue by galgalesh** [bhdouglass/uappexplorer#79]
1. Go to https://uappexplorer.com/apps?type=application
2. Click on the most bottom-right app.
3. Click next (you first app of second page of results). Click next again and you get the same app.

PS: Awesome website, thanks for making this!

**Comment by bhdouglass** [comment]
Darn, I'm seeing that issue as well. I'll get it fixed!

**Comment by bhdouglass** [comment]
Just fixed this, let me know if you come across any other issues!
