### ISSUE TITLE
Install button should go to app page, not search

### ISSUE THREAD

**Issue by galgalesh** [bhdouglass/uappexplorer#80]
The install button should go to the app page in the store scope instead of searching for the app name.

I understand this is probably a limitation to the scope itself but I'd like a place to track the upstream bug so I can go and put myself as "affected".

**Comment by bhdouglass** [comment]
You are correct, this is a limitation of the scopes api. I've already filed a bug for this here: https://bugs.launchpad.net/ubuntu/+source/unity-scopes-api/+bug/1492252
Fell free to mark it as affects you. It has gained some momentum recently, hopefully it will arrive in an OTA update soon.

**Comment by bhdouglass** [comment]
Closing this as I don't think the Ubuntu Touch phone will support this given the recent news that Canonical won't be driving Ubuntu Touch any more.
