### ISSUE TITLE
Layout garbled when app has big title

### ISSUE THREAD

**Issue by galgalesh** [bhdouglass/uappexplorer#81]
As you can see in the screenshot, some app names disappear behind the ratings start. I think the ratings section should just be pushed down when the name becomes too large...

Meizi PRO 5

![screenshot20160813_123316906](https://cloud.githubusercontent.com/assets/1492981/17642740/44369a86-6152-11e6-93ef-75a66d72a998.png)

**Comment by bhdouglass** [comment]
Thanks for the heads up, I'll look into this!

**Comment by bhdouglass** [comment]
I just fixed this, looks fine on my mx4. Let me know if you notice any other issues!
