### ISSUE TITLE
Reviews aren't refreshed - only new ones added

### ISSUE THREAD

**Issue by flota113** [bhdouglass/uappexplorer#82]
I saw code responsible for scheduling reviews refreshing every hour - unfortunately it does only adds new ones (not sure but I think it doesn't add new ones even - or it's scheduled for longer than hour? )
It's almost a week now and text and stars for reviews hasn't been refreshed.

On uappexplorer.com:
![appsrating](https://cloud.githubusercontent.com/assets/3848216/17675096/791ff97c-6328-11e6-9e3f-5c49201684f0.png)

while on store:
![appsrating2](https://cloud.githubusercontent.com/assets/3848216/17675095/791cda1c-6328-11e6-99e4-86e9c3997c3f.png)

Used app:
https://uappexplorer.com/app/movietime.flotynski
https://uappexplorer.com/api/apps/reviews/movietime.flotynski

store api:
https://reviews.ubuntu.com/click/api/1.0/reviews/?package_name=movietime.flotynski

**Comment by bhdouglass** [comment]
It should be updating every 24 hours, not hourly: https://github.com/bhdouglass/uappexplorer/blob/master/src/spider/spider.js#L49

And since the last review was 2016-08-14T13:45:08.586Z, I wouldn't be concerned about it missing until tomorrow.

**Comment by flota113** [comment]
Ok, misunderstood code, but some reviews were changed by users at 12 aug 2016 so more than 24 hours - is this also how it supposed to be?

**Comment by bhdouglass** [comment]
Actually, it looks like it's been updated since your last comment. Seems to be up to date now.
