### ISSUE TITLE
Search from pages 2 or more don't show result

### ISSUE THREAD

**Issue by kazord** [bhdouglass/uappexplorer#83]
On web version
Use search input from a preview search (or display) after changed page to 2nd or 3pages make search result invisible (maybe filtered by page=n parameters)

**Comment by bhdouglass** [comment]
Thanks for the bug report, I do see the issue (though I thought this was fixed!). I'll get a fix for this soon.

**Comment by bhdouglass** [comment]
I just fixed this, let me know if you have any other issues!
