### ISSUE TITLE
App copyright infringement

### ISSUE THREAD

**Issue by pctroll** [bhdouglass/uappexplorer#84]
Hello,

The following app is infringing copyright from my published book and game. I'd like to request this app be removed from the store and send a cease and desist to the author, as I am no affiliated to Paco Mulas in any way.

uApp Explorer app: https://uappexplorer.com/app/breakertouch.fmulcar
My Game: https://pctroll.itch.io/html5-breaker
My Book: https://leanpub.com/brick-breaker-phaser

In the book I give credit to Kenney and every people involved in the process (even official reviewers). It is a shame that the said author cannot even create a different logo and change the assets.

**Comment by bhdouglass** [comment]
I'm sorry this app is infringing on your copyright. Unfortunately uApp Explorer can't do much for you here as the app and store itself is hosted by Canonical, uApp Explorer is just a browser for the apps.

I would suggest that you first reach out to the author of the app via the support link on this page: https://uappexplorer.com/app/breakertouch.fmulcar . If that doesn't go anywhere I would then suggest reaching out to Canonical (http://www.canonical.com/).

**Comment by bhdouglass** [comment]
Since it appears that the app has changed it's logo I'm going to assume that your issue has been resolved. So I'm going to close this ticket. If you run into any other issues, feel free to reach out!
