### ISSUE TITLE
Leaving a review?

### ISSUE THREAD

**Issue by micolito** [bhdouglass/uappexplorer#85]
I would like to leave a review for a couple apps, however, I can't figure out how.
I see reviews, on both my ubuntu tablet, and on my mac using chrome.
However, I see no method to leave a new review.
Do I need to do something to enable this feature?

**Comment by bhdouglass** [comment]
Since uApp Explorer is just an app viewer, you can't leave reviews for apps on the site. If you want to leave a review for an app you'll need to do that from your ubuntu tablet. If you long press on an app in the app list it will take you to a page where you can leave a review.
