### ISSUE TITLE
author filter too lax

### ISSUE THREAD

**Issue by apachelogger** [bhdouglass/uappexplorer#86]
When clicking on the 'more apps by: foo' link at the bottom of a snap's page the search page one ends up with employs an overly lax filter, matching *foo* rather than strictly foo.

For example for 
https://uappexplorer.com/app/kblocks.kde
leads to
https://uappexplorer.com/apps?q=author%3AKDE&type=all_types&sort=-points
which lists
https://uappexplorer.com/app/simplecryptedmemo.michal-valdman
authored by "nikde" rather than "kde"

**Comment by bhdouglass** [comment]
You're right, that should be an exact match, I'll get that updated.

**Comment by bhdouglass** [comment]
I just fixed this, the author filter is now an exact match.

**Comment by apachelogger** [comment]
Thanks! Works like a charm :+1:
