### ISSUE TITLE
Using the old URL.

### ISSUE THREAD

**Issue by luk3yx** [bhdouglass/uappexplorer#90]
Hello,

uappexplorer uses https://myapps.developer.ubuntu.com, rather than https://dashboard.snapcraft.io. This means that new updates to snaps won't be shown.
Can this be fixed at all?

Thanks,

luk3yx

**Comment by bhdouglass** [comment]
Yeah and update is in the works for moving over to the new snaps api to get thing running smoothly again.

**Comment by bhdouglass** [comment]
I've recently updated uApp Explorer to use the new snap APIs, so you can find all the snaps here: https://uappexplorer.com/snaps
