### ISSUE TITLE
Exploration and support for the ubports openstore in uappexplorer

### ISSUE THREAD

**Issue by bastos77** [bhdouglass/uappexplorer#91]
I like the uappexplorere very much and it is for me much more convenient than the cannical store or the openstore. So i would appreciate very much if the apps hosted in openstore would be explored shown and discussed also in uappexplorer.

**Comment by bhdouglass** [comment]
OpenStore integration currently in progress and I hope to have it ready soon!

**Comment by bhdouglass** [comment]
I just finished this the other day, enjoy!

**Comment by bastos77** [comment]
Yes. Great! The app also works. Thanks :)
