### ISSUE TITLE
uappexplorer shows todays date has published date

### ISSUE THREAD

**Issue by Alculete** [bhdouglass/uappexplorer#94]
Every snap app on uappexplorer shows today's date making it impossible to track update date.

Se images bellow. the same file package CLI and from uaapexplorer

# **Information from CLI**
![libreoffice cli](https://user-images.githubusercontent.com/2129497/27839670-5d18651a-60f3-11e7-867f-5346459e3642.png)

# **Information from uappexplorer**
![libreoffice uappexplorer](https://user-images.githubusercontent.com/2129497/27839669-5d13e986-60f3-11e7-9cc4-3ed2225bb6d5.png)

**Comment by bhdouglass** [comment]
This is unfortunately due to the snap store api, I'm currently waiting on a fix from them. But feel free to bug your favorite snap store Dev and/or the snap forum to let them know there is interest in getting the published and updated dates back in the api.

**Comment by noise** [comment]
@bhdouglass can you please file a bug at https://bugs.launchpad.net/snapstore with the specific endpoint and field details?  Thanks!

**Comment by niemeyer** [comment]
Also, can you join our thread here, if you have the time, just to say hi and to establish a point of contact for similar issues in the future:

https://forum.snapcraft.io/t/snaps-updates-date-removed-from-api/1225

**Comment by bhdouglass** [comment]
@noise done! https://bugs.launchpad.net/snapstore/+bug/1702604
I previously spoke about this with Kit, so apologies if this is duplicated in a different location.

@niemeyer thanks for the invite!

**Comment by cjwatson** [comment]
This should work again for you as of yesterday evening.

**Comment by bhdouglass** [comment]
Wonderful, thank you! uApp Explorer is now back to normal.
