### ISSUE TITLE
Switching between PHONE APPS and SNAPS

### ISSUE THREAD

**Issue by daylightbrightledlight** [bhdouglass/uappexplorer#96]
When switching between PHONE APPS and SNAPS on the top left of the website, the query that was searched is removed. The website should not discard the query when switching from PHONE APPS and SNAPS.

Process:
1. Go to https://uappexplorer.com/apps?q=test&sort=relevance
2. Press on SNAPS toggle button

Notice how the `test` query is removed and goes to https://uappexplorer.com/snaps. The expected result of pressing the button should be https://uappexplorer.com/snaps?q=test&sort=relevance.

The same happens when pressing the PHONE APPS button.

**Comment by bhdouglass** [comment]
This is a good idea, I'll let you know when it's implemented!

**Comment by daylightbrightledlight** [comment]
@bhdouglass Okay. Thanks!

**Comment by daylightbrightledlight** [comment]
Closing issue because uApp Explorer has shutdown.
