### ISSUE TITLE
support_url field in API response for snaps will be deprecated

### ISSUE THREAD

**Issue by Roadmaster** [bhdouglass/uappexplorer#97]
Hello!

As documented in https://bugs.launchpad.net/snapstore/+bug/1666792, API responses for snap details now contain a "contact" field, which should be used preferentially over support_url, and labelled as "Contact" in a snap's presentation page.

For now, this field contains the same information as support_url but will soon become empty for all responses, and eventually disappear (see the bug for some rationale on this).

Could you please update uApp Explorer so it takes these API changes into account?

Thanks!

**Comment by bhdouglass** [comment]
Thanks for the heads up, I'll get uApp Explorer moved over to using the new field.

**Comment by bhdouglass** [comment]
Just pushed an update for this, thanks!
